name: canteen_food_ordering_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  firebase_storage: ^3.1.6
  fluttertoast: ^7.0.2
  uuid: 2.2.0
  path: ^1.6.4
  progress_dialog: ^1.2.4
  curved_navigation_bar: ^0.3.3
  razorpay_flutter: ^1.2.2
  flutter_launcher_icons: "^0.7.0"

  flutter_barcode_scanner: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
